"use strict";

var arrEquations = [
// Ecuacion 0
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082 &rarr; C\u2084H\u2089OH</h1>\n        \n                <h2 class=\"center small_padding\">Paso 1: Asignar los n\xFAmeros de oxidaci\xF3n de cada mol\xE9cula</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion1/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo):</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CHO<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "1", "-2"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082 &rarr; C\u2084H\u2089OH</h1>\n        \n                <h2 class=\"center small_padding\">Paso 2: Agregar uno de los hidr\xF3genos a donde est\xE1 el doble enlace del carbono</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion1/paso1.png\"></p>\n                <p class=\"center\">Ese carbono quedar\xE1 con un <span style=\"color: #F95759\">enlace simple</span> y con dos <span style=\"color: #F95759\">hidr\xF3genos</span>.</p>\n                <p class=\"center\">Escribe la ecuaci\xF3n con el <span style=\"color: #F95759\">hidr\xF3geno agregado</span>:</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083 - CH\u2082 - CH\u2082 - <input id=\"answer\" type=\"text\" class=\"big_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["CH2O"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082 &rarr; C\u2084H\u2089OH</h1>\n        \n                <h2 class=\"center small_padding\">Paso 3: Asignar la carga formal de los \xE1tomos</h2>\n                <p class=\"center\">Escribe la carga formal del <span style=\"color: #F95759\">ox\xEDgeno</span>:</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083 - CH\u2082 - CH\u2082 - CH\u2082 - O <input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082 &rarr; C\u2084H\u2089OH</h1>\n        \n                <h2 class=\"center small_padding\">Paso 4: Agregar el otro hidr\xF3geno al ox\xEDgeno</h2>\n                <p class=\"center\">En este caso tiene un electr\xF3n disponible y puede crear <span style=\"color: #F95759\">otro enlace</span>.</p>\n                <p class=\"center\">Escribe c\xF3mo quedar\xEDa el ox\xEDgeno <span style=\"color: #F95759\">enlazado</span> al hidr\xF3geno:</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083 - CH\u2082 - CH\u2082 - CH\u2082 - <input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["OH"]
    }, {
        "num": 4,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082 &rarr; C\u2084H\u2089OH</h1>\n        \n                <h2 class=\"center small_padding\">Paso 5: Asignar el n\xFAmero de oxidaci\xF3n del producto</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion1/paso5.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula:</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    OH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "-2", "0"]
    }, {
        "num": 5,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082 &rarr; C\u2084H\u2089OH</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion1/paso6.png\"></p>\n                <p class=\"center\">\n                    En este caso, la reacci\xF3n pasa de tener -8 a -9 de carga, significa que gana electrones,\n                    entonces se trata de una <span style=\"color: #F95759\">reducci\xF3n</span>.\n                </p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],
// Ecuacion 1
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + Cl\u2082 &rarr; C\u2084H\u2088Cl\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Paso 1: Asignar los n\xFAmeros de oxidaci\xF3n de cada mol\xE9cula</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion2/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo):</p>\n                <p class=\"center\"><span style=\"color: #F95759\">PISTA:</span> En el caso de los hal\xF3genos, su n\xFAmero de oxidaci\xF3n ser\xE1 0 ya que son iones. Cuando est\xE1n formando una mol\xE9cula es cuando aplica su n\xFAmero de oxidaci\xF3n.</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    Cl\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-1", "-1", "-3", "0"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + Cl\u2082 &rarr; C\u2084H\u2088Cl\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Paso 2: Agregar los dos cloros a donde est\xE1n los dos carbonos que comparten el doble enlace</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion2/paso1.png\"></p>\n                <p class=\"center\">Ese carbono quedar\xE1 con un <span style=\"color: #F95759\">enlace simple</span>, con un hidr\xF3geno y con un cloro.</p>\n                <p class=\"center\">Escribe la ecuaci\xF3n con el <span style=\"color: #F95759\">hidr\xF3geno agregado</span>:</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083 - <input id=\"answer\" type=\"text\" class=\"big_input big_text\"> -\n                    <input id=\"answer\" type=\"text\" class=\"big_input big_text\"> - CH\u2083\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["CHCl", "CHCl"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + Cl\u2082 &rarr; C\u2084H\u2088Cl\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Paso 3: Asignar los n\xFAmeros de oxidaci\xF3n del producto</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion2/paso3.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula:</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CHCl<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CHCl<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "0", "0", "-3"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + Cl\u2082 &rarr; C\u2084H\u2088Cl\u2082</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion2/paso4.png\"></p>\n                <p class=\"center\">\n                    La reacci\xF3n pasa de tener los CH en -1 a CHCl en 0 por lo que\n                    ocurre una <span style=\"color: #F95759\">oxidaci\xF3n</span>, ya que gana electrones.\n                </p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],
// Ecuacion 2
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082O &rarr; C\u2084H\u2088O\u2082 + H\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Paso 1: Asignar los n\xFAmeros de oxidaci\xF3n de cada mol\xE9cula</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion3/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo):</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CHO<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082O<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "1", "-1"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082O &rarr; C\u2084H\u2088O\u2082 + H\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Paso 2: Agregar el OH y/o el hidr\xF3geno al carbono que tiene el doble enlace con el ox\xEDgeno</h2>\n                <p class=\"center\">\n                    La mol\xE9cula de agua se separa en <span style=\"color: #F95759\">H-OH</span>.\n                    El \xE1tomo de ox\xEDgeno se va a unir con el CH que tiene el <span style=\"color: #F95759\">doble enlace</span> con el ox\xEDgeno.\n                </p>\n                <p class=\"center\">\n                    Escribe la ecuaci\xF3n con el <span style=\"color: #F95759\">OH</span>\n                    y/o <span style=\"color: #F95759\">hidr\xF3geno</span> agregado:\n                </p>\n                <div class=\"center big_text small_padding\">\n                    CH\u2083 - CH\u2082 - CH\u2082 - <input id=\"answer\" type=\"text\" class=\"big_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["COOH"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082O &rarr; C\u2084H\u2088O\u2082 + H\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Paso 3: Asignar los n\xFAmeros de oxidaci\xF3n del producto</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion3/paso3.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo si el n\xFAmero de oxidaci\xF3n es diferente de 0):</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    COOH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "2", "0"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O + H\u2082O &rarr; C\u2084H\u2088O\u2082 + H\u2082</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion3/paso4.png\"></p>\n                <p class=\"center\">\n                    La reacci\xF3n paso de tener -7 a -5, es decir, pierde electrones.\n                    Por lo tanto, es una <span style=\"color: #F95759\">oxidaci\xF3n</span>.\n                </p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],
// Ecuacion 3
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + H\u2082 &rarr; C\u2084H\u2081\u2080</h1>\n        \n                <h2 class=\"center small_padding\">Paso 1: Asignar los n\xFAmeros de oxidaci\xF3n de cada mol\xE9cula</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion4/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo):</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-1", "-1", "-3", "-2"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + H\u2082 &rarr; C\u2084H\u2081\u2080</h1>\n        \n                <h2 class=\"center small_padding\">Paso 2: Agregar los dos hidr\xF3genos a donde est\xE1n los carbonos que comparten el doble enlace</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion4/paso1.png\"></p>                \n                <p class=\"center\">\n                    Quedan esos dos carbonos con un <span style=\"color: #F95759\">enlace simple</span>\n                    y con dos <span style=\"color: #F95759\">hidr\xF3genos</span> enlazados a ellos.\n                </p>\n                <p class=\"center\">\n                    Escribe la ecuaci\xF3n con los <span style=\"color: #F95759\">hidr\xF3genos</span> agregados:\n                </p>\n                <div class=\"center big_text small_padding\">\n                    CH\u2083 - <input id=\"answer\" type=\"text\" class=\"big_input big_text\"> - <input id=\"answer\" type=\"text\" class=\"big_input big_text\"> - CH\u2083\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["CH2", "CH2"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + H\u2082 &rarr; C\u2084H\u2081\u2080</h1>\n        \n                <h2 class=\"center small_padding\">Paso 3: Asignar los n\xFAmeros de oxidaci\xF3n del producto</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion4/paso3.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo si el n\xFAmero de oxidaci\xF3n es diferente de 0):</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "-3"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088 + H\u2082 &rarr; C\u2084H\u2081\u2080</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion4/paso4.png\"></p>\n                <p class=\"center\">\n                    La reacci\xF3n pas\xF3 de tener -8 a -10, es decir, gana electrones.\n                    Por lo tanto, es una <span style=\"color: #F95759\">reducci\xF3n</span>.\n                </p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],
// Ecuacion 4
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>CH\u2084 + []O\u2082 &rarr; CO\u2082 + []H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Paso 1: Balancear la reaci\xF3n</h2>\n                <p class=\"center\">Completa en cada campo de texto el coeficiente de la mol\xE9cula:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2084 + <input id=\"answer\" type=\"text\" class=\"small_input big_text\">O\u2082 &rarr; CO\u2082 + <input id=\"answer\" type=\"text\" class=\"small_input big_text\">H\u2082O\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["2", "2"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>CH\u2084 + 2O\u2082 &rarr; CO\u2082 + 2H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Paso 2: Asignar los n\xFAmeros de oxidaci\xF3n de cada mol\xE9cula</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion5/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo):</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2084<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    2(O\u2082)<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-4", "0"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>CH\u2084 + 2O\u2082 &rarr; CO\u2082 + 2H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Paso 3: Agregar los ox\xEDgenos a los reactivos de la reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion5/paso2.png\"></p>                \n                <p class=\"center\">\n                    Se rompen los <span style=\"color: #F95759\">doble enlaces</span> de los dos pares de ox\xEDgenos.\n                    Dos de los ox\xEDgenos se van a ir con el <span style=\"color: #F95759\">carbono</span>.\n                    Los otros dos se van a unir con dos de los cuatro <span style=\"color: #F95759\">hidr\xF3genos libres</span> que quedan.\n                </p>\n                <p class=\"center\">\n                    Escribe como quedar\xEDa la reacci\xF3n con los ox\xEDgenos ya <span style=\"color: #F95759\">enlazados</span>:\n                </p>\n                <div class=\"center big_text small_padding\">\n                    <input id=\"answer\" type=\"text\" class=\"big_input big_text\"> + <input id=\"answer\" type=\"text\" class=\"big_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["CO2", "H2O"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>CH\u2084 + 2O\u2082 &rarr; CO\u2082 + 2H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Paso 4: Asignar los n\xFAmeros de oxidaci\xF3n del producto</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion5/paso3.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el <span style=\"color: #F95759\">n\xFAmero de oxidaci\xF3n</span> de la mol\xE9cula (recuerda escribir el signo si el n\xFAmero de oxidaci\xF3n es diferente de 0):</p>\n                \n                <div class=\"center big_text small_padding\">\n                    CO\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    2(H\u2082O)<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["2", "-2"]
    }, {
        "num": 4,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>CH\u2084 + 2O\u2082 &rarr; CO\u2082 + 2H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion5/paso4.png\"></p>\n                <p class=\"center\">\n                    La reacci\xF3n paso de tener -4 a 0, es decir, pierde electrones.\n                    Por lo tanto, es una <span style=\"color: #F95759\">oxidaci\xF3n</span>.\n                </p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],
// Ecuacion 5
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O  + H\u2082O &rarr; C\u2084H\u2088O\u2082 + H\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 1:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion6/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los reactivos de la reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CHO<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082O<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "1", "-1"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O  + H\u2082O &rarr; C\u2084H\u2088O\u2082 + H\u2082</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 1:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion6/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los productos de la  reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    COOH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "2", "0"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2084H\u2088O  + H\u2082O &rarr; C\u2084H\u2088O\u2082 + H\u2082</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion6/paso1.png\"></p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],

// Ecuacion 6
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2085H\u2081\u2080O + H\u2082 &rarr; C\u2085H\u2081\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 2:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion7/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los reactivos de la reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    C=O<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "2", "-3", "0"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2085H\u2081\u2080O + H\u2082 &rarr; C\u2085H\u2081\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 2:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion7/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los productos de la  reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    OH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-2", "-2", "-1", "0", "-3"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2085H\u2081\u2080O + H\u2082 &rarr; C\u2085H\u2081\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion7/paso1.png\"></p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],

// Ecuacion 7
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2086H\u2081\u2082 + H\u2082O  &rarr; C\u2086H\u2081\u2084O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 3:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion8/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los reactivos de la reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    C=C<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082O<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-3", "0", "-3", "-3", "-1"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2086H\u2081\u2082 + H\u2082O  &rarr; C\u2086H\u2081\u2084O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 3:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion8/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los productos de la  reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH-C<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    OH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-3", "-1", "-3", "-3", "0"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2086H\u2081\u2082 + H\u2082O  &rarr; C\u2086H\u2081\u2084O</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion8/paso1.png\"></p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],

// Ecuacion 8
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>HC\xAD\u2261CH + H\u2082 &rarr; CH\u2082=CH\u2082 + H\u2082 &rarr; CH\u2083-CH\u2083</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 4:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion9/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los reactivos de la reacci\xF3n:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-1", "-1", "0"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>HC\xAD\u2261CH + H\u2082 &rarr; CH\u2082=CH\u2082 + H\u2082 &rarr; CH\u2083-CH\u2083</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 4:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion9/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los intermediarios de la  reacci\xF3n:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-2", "-2", "0"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>HC\xAD\u2261CH + H\u2082 &rarr; CH\u2082=CH\u2082 + H\u2082 &rarr; CH\u2083-CH\u2083</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 4:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion9/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los reactivos de la  reacci\xF3n:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CH\u2083<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-3", "-3"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>HC\xAD\u2261CH + H\u2082 &rarr; CH\u2082=CH\u2082 + H\u2082 &rarr; CH\u2083-CH\u2083</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion9/paso1.png\"></p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],

// Ecuacion 9
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n        \n                <h2 class=\"center small_padding\">Ejercicio 5:</h2>             \n                <p class=\"center\">Balancea la reacci\xF3n:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    C\u2083H\u2088 + <input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    O\u2082 &rarr; <input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CO\u2082 + <input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082O\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["5", "3", "4"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2083H\u2088 + 5O\u2082 &rarr; 3CO\u2082 + 4H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 5:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion10/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los reactivos de la reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    C\u2083H\u2088<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    5(O\u2082)<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-8", "0"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2083H\u2088 + 5O\u2082 &rarr; 3CO\u2082 + 4H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 5:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion10/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los productos de la  reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    3(CO\u2082)<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    4(H\u2082O)<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["6", "-4"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2083H\u2088 + 5O\u2082 &rarr; 3CO\u2082 + 4H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion10/paso1.png\"></p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }],
// Ecuacion 10
    [{
        "num": 0,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n        \n                <h2 class=\"center small_padding\">Ejercicio 6:</h2>             \n                <p class=\"center\">Balancea la reacci\xF3n:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    C\u2081\u2086H\u2083\u2084 + (<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    /<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    )O\u2082 &rarr; <input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    CO\u2082 + <input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    H\u2082O \n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["49", "2", "16", "17"]
    }, {
        "num": 1,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2081\u2086H\u2083\u2084 + (49/2)O\u2082 &rarr; 16CO\u2082 + 17H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 6:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion11/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los reactivos de la reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    C\u2081\u2086H\u2083\u2084<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    (49/2)O\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["-34", "0"]
    }, {
        "num": 2,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2081\u2086H\u2083\u2084 + (49/2)O\u2082 &rarr; 16CO\u2082 + 17H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">Ejercicio 6:</h2>             \n                <p class=\"center\"><img src=\"img/pasos/reaccion11/paso1.png\"></p>\n                <p class=\"center\">Completa en cada campo de texto el n\xFAmero de oxidaci\xF3n de los productos de la  reaccion:</p>\n                        \n                <div class=\"center big_text small_padding\">\n                    16CO\u2082<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                    17H\u2082O<input id=\"answer\" type=\"text\" class=\"small_input big_text\">\n                </div>\n                <div>\n                    <p id=\"feedback\" class=\"feedback\">placeholder</p>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                    <button id=\"avanzar\" class=\"big_right normal\">Avanzar</button>\n                </div>\n            </div>\n        ",
        "answers": ["32", "-17"]
    }, {
        "num": 3,
        "attempts": 0,
        "content": "\n            <div id=\"slide\" class=\"container\">\n                <button id=\"salir\" class=\"small_right danger\">Salir</button>\n                <button id=\"recordatorio\" class=\"small_left normal\">Ver recordatorio</button>\n                <h1>C\u2081\u2086H\u2083\u2084 + (49/2)O\u2082 &rarr; 16CO\u2082 + 17H\u2082O</h1>\n        \n                <h2 class=\"center small_padding\">\xA1Muy bien! Has terminado con esta reacci\xF3n</h2>\n                <p class=\"center\"><img src=\"img/pasos/reaccion11/paso1.png\"></p>\n                \n                <div>\n                    <button id=\"regresar\" class=\"big_left normal\">Regresar</button>\n                </div>\n            </div>\n        ",
        "answers": []
    }]];